set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR loongarch64)

set(LOONGARCH_TOOLCHAIN_ROOT "/opt/atk-dl2k0300-toolchain" CACHE PATH "龙芯交叉编译工具链")
set(CMAKE_C_COMPILER "${LOONGARCH_TOOLCHAIN_ROOT}/bin/loongarch64-linux-gnu-gcc")
set(CMAKE_CXX_COMPILER "${LOONGARCH_TOOLCHAIN_ROOT}/bin/loongarch64-linux-gnu-g++")

# 必须改成开发板根文件系统或SDK sysroot的真实路径。
set(CMAKE_SYSROOT "${LOONGARCH_TOOLCHAIN_ROOT}/sysroot" CACHE PATH "开发板sysroot")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
set(CMAKE_CXX_FLAGS_INIT "--sysroot=${CMAKE_SYSROOT}")
